version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "${COMPOSE_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - my_network

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    working_dir: /var/www/html/backend
    volumes:
      - .:/var/www/html
    networks:
      - my_network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${COMPOSE_MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${COMPOSE_MYSQL_DATABASE}"
      MYSQL_USER: "${COMPOSE_MYSQL_USER}"
      MYSQL_PASSWORD: "${COMPOSE_MYSQL_PASSWORD}"
    ports:
      - "${COMPOSE_MYSQL_PORT}:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - my_network

  redis:
    image: redis:alpine
    restart: always
    command: [ "sh", "-c", "exec redis-server --requirepass \"${REDIS_PASSWORD}\"" ]
    volumes:
      - "./docker/redis/data:/data"
    ports:
      - "${COMPOSE_REDIS_PORT}:6379"
    networks:
      - my_network

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    command: "python /python/bot/bot.py"
    volumes:
      - ./python/bot:/python/bot
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${COMPOSE_FRONTEND_PORT}:80"

networks:
  my_network:
    driver: bridge